### ISSUE TITLE
Adicionar ao F-Droid

### ISSUE THREAD

**Issue by pizzamaker** [MikaelMello/argumentopas#2]
Seria muito bacana ter esse app no F-Droid, que é uma espécie de Google Play mas com apenas software livre: https://f-droid.org/

Aqui tem instruções de como adicioná-lo à fila de inclusão: https://f-droid.org/contribute/

**Comment by mikaelmello** [comment]
Acho a ideia muito boa, porém não gostaria que meu aplicativo fosse redistribuído por terceiros e acho que por isso ele não se qualificaria para ser um FOSS.
